clone:
  skip_verify: true
build:
  image: index.shurenyun.com/solo:on-build
  commands:
    - mvn install
publish:
  upload:
    image: registry:5000/library/drone-upload:latest
    server: http://192.168.99.103:8900
    target_file: target/solo.war
    bapp_id: 1
    yearmonth_id: 1
